spring.datasource.url=jdbc:postgresql://localhost:5433/banking
spring.datasource.username=postgres
spring.datasource.password=accelerate

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081